# This is an example config containing information for the preselection

ntuple_path: "root://cmsxrootd-kit-disk.gridka.de//store/user/nshadskiy/CROWN/ntuples/02_2024_nmssm_v4/CROWNRun"
friends: ["fake_factors_v1","mass_fits_v2"]
era: "2018"
channel: "mt"
tree: "ntuple"
event_split: "even"

output_path: "/ceph/nshadskiy/nmssm_ml/02_2024_v2_reduced"

processes:
    HToTauTau:
        tau_gen_modes:
            - "all"
        samples:
            - "GluGluHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "VBFHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X"

    HToBB:
        tau_gen_modes:
            - "all"
        samples:
            - "GluGluHToBB_M-125_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "VBFHToBB_M-125_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X"
    
    VH:
        tau_gen_modes:
            - "all"
        samples:
            - "ZHToTauTau_M125_CP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X"
            # - "ZH_HToBB_ZToLL_M-125_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "WminusHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "WplusHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X"

    DYjets:
        tau_gen_modes:
            - "L"
        samples:
            - "DYJetsToLL_M-10to50_TuneCP5_13TeV-madgraphMLM-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "DY1JetsToLL_M-50_MatchEWPDG20_TuneCP5_13TeV-madgraphMLM-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "DY2JetsToLL_M-50_MatchEWPDG20_TuneCP5_13TeV-madgraphMLM-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "DY3JetsToLL_M-50_MatchEWPDG20_TuneCP5_13TeV-madgraphMLM-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "DY4JetsToLL_M-50_MatchEWPDG20_TuneCP5_13TeV-madgraphMLM-pythia8_RunIISummer20UL18NanoAODv9-106X"

    diboson:
        tau_gen_modes:
            - "L"
        samples:
            - "ZZ_TuneCP5_13TeV-pythia8_RunIISummer20UL18NanoAODv9-106X" 
            - "WW_TuneCP5_13TeV-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "WZ_TuneCP5_13TeV-pythia8_RunIISummer20UL18NanoAODv9-106X"

    ttbar:
        tau_gen_modes:
            - "L"
        samples:
            - "TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "TTToHadronic_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X"

    ST:
        tau_gen_modes:
            - "L"
        samples:
            - "ST_t-channel_antitop_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "ST_t-channel_top_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X"
    
    embedding:
        tau_gen_modes:
            - "all"
        samples:
            - "TauEmbedding-MuTauFinalState_Run2018A-UL2018"
            - "TauEmbedding-MuTauFinalState_Run2018B-UL2018"
            - "TauEmbedding-MuTauFinalState_Run2018C-UL2018"
            - "TauEmbedding-MuTauFinalState_Run2018D-UL2018"

    tau_fakes:
        tau_gen_modes:
            - "all"
        samples:
            - "SingleMuon_Run2018A-UL2018_GT36"
            - "SingleMuon_Run2018B-UL2018_GT36"
            - "SingleMuon_Run2018C-UL2018_GT36"
            - "SingleMuon_Run2018D-UL2018_GT36"

    XToYHTo2Tau2B:
        tau_gen_modes:
            - "all"
        samples:
            - "NMSSM_XToYHTo2Tau2B_MX-massX_MY-massY_TuneCP5_13TeV-madgraph-pythia8_RunIISummer20UL18NanoAODv9-106X"

    XToYHTo2B2Tau:
        tau_gen_modes:
            - "all"
        samples:
            - "NMSSM_XToYHTo2B2Tau_MX-massX_MY-massY_TuneCP5_13TeV-madgraph-pythia8_RunIISummer20UL18NanoAODv9-106X"

general_event_selection:
    had_tau_pt: "pt_2 > 30"
    had_tau_eta: "abs(eta_2) < 2.3"
    had_tau_decay_mode: "(tau_decaymode_2 == 0) || (tau_decaymode_2 == 1) || (tau_decaymode_2 == 10) || (tau_decaymode_2 == 11)"
    had_tau_id_vs_ele: "id_tau_vsEle_VVLoose_2 > 0.5"
    had_tau_id_vs_mu: "id_tau_vsMu_Tight_2 > 0.5"
    lep_pt: "pt_1 > 25"
    single_trigger: "(trg_single_mu24 > 0.5) || (trg_single_mu27 > 0.5)"
    lep_iso: "iso_1 < 0.15"
    tau_pair_sign: "(q_1*q_2) < 0" 
    no_extra_lep: "(extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)"
    boosted_tau_veto: "(boosted_deltaR_ditaupair > 0.8) || (boosted_deltaR_ditaupair < 0.1)"

special_event_selection:
    had_tau_id_vs_jet: ["id_tau_vsJet_Medium_2 > 0.5", "(id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)"]
    good_bb_pair: "(bpair_pt_1>=20 && bpair_pt_2>=20 && nbtag>=1 && abs(bpair_eta_2)<=2.5) || ((fj_Xbb_particleNet_XbbvsQCD>=0.6) && abs(fj_Xbb_eta)<=2.5 && fj_Xbb_pt>=200)"

mc_weights:
    # general weights: string is passed directly as weight
    # pileup: "puweight"
    lep_iso: "iso_wgt_mu_1"
    lep_id: "id_wgt_mu_1"
    had_tau_id_vs_ele: (gen_match_2==5) * ((id_tau_vsEle_VVLoose_2>0.5)*id_wgt_tau_vsEle_VVLoose_2 + (id_tau_vsEle_VVLoose_2<0.5)) + (gen_match_2!=5)
    had_tau_id_vs_mu: (gen_match_2==5) * ((id_tau_vsMu_Tight_2>0.5)*id_wgt_tau_vsMu_Tight_2 + (id_tau_vsMu_Tight_2<0.5)) + (gen_match_2!=5)
    single_trigger: "trg_wgt_single_mu24ormu27"
    
    # special weights: these are not generally applied, e.g. only for a specific process or era
    # here the string is a needed information to apply the weight -> see corresponding functions
    # generator: "stitching"
    # lumi: ""
    Z_pt_reweighting: "ZPtMassReweightWeight"
    Top_pt_reweighting: "topPtReweightWeight"

emb_weights:
    # general weights (for embedding): string is passed directly as weight
    # generator: "emb_genweight * emb_idsel_wgt_1 * emb_idsel_wgt_2 * emb_triggersel_wgt"
    lep_iso: "iso_wgt_mu_1"
    lep_id: "id_wgt_mu_1"
    single_trigger: "trg_wgt_single_mu24ormu27"

masses_X: [240,280,300,320,360,400,450,500,550,600,650,700,750,800,850,900,950,1000,1100,1200,1300,1400,1500,1600,1700,1800,1900,2000,2200,2400,2500,2600,2800,3000,3500,4000]
masses_Y: [60,70,80,90,100,125,150,250,300,400,500,600,700,800,900,1000,1100,1200,1300,1400,1600,1800,2000,2200,2400,2500,2600,2800]
# masses_X: [280, 450, 800, 1200, 2000, 4000]
# masses_Y: [70, 125, 250, 500, 1000, 1600, 2800]
# masses_X: [240,280]
# masses_Y: [60,70,80,90]

output_feature:
    - "weight"
    - "massX"
    - "massY"
    - "njets"
    - "nbtag"
    - "nfatjets"
    - "pt_1"
    - "pt_2"
    - "eta_1"
    - "phi_1"
    - "eta_2"
    - "phi_2"
    - "deltaR_ditaupair"
    - "m_vis"
    - "mt_1"
    # - "deltaPhi_met_tau1"
    # - "deltaPhi_met_tau2"
    - "m_fastmtt"
    - "pt_fastmtt"
    - "eta_fastmtt"
    - "phi_fastmtt"
    - "bpair_pt_1"
    - "bpair_eta_1"
    - "bpair_phi_1"
    - "bpair_btag_value_1"
    - "bpair_pt_2"
    - "bpair_eta_2"
    - "bpair_phi_2"
    - "bpair_btag_value_2"
    - "bpair_m_inv"
    - "bpair_deltaR"
    - "bpair_pt_dijet"
    - "fj_Xbb_pt"
    - "fj_Xbb_eta"
    - "fj_Xbb_phi"
    - "fj_Xbb_msoftdrop"
    - "fj_Xbb_nsubjettiness_2over1"
    - "fj_Xbb_nsubjettiness_3over2"
    - "met"
    - "metphi"
    - "mass_tautaubb"
    - "pt_tautaubb"
    - "jpt_1"
    - "jpt_2"
    - "mjj"
    - "kinfit_mX"
    - "kinfit_mY"
    - "kinfit_chi2"